services:
  portfolio:
    container_name: emilija.dev
    image: ganglem/vs-code-portfolio:latest
    env_file:
      - .env
    networks:
      - web
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.emilija-dev.rule=Host(`emilija.dev`)
      - traefik.http.routers.emilija-dev.entrypoints=websecure
      - traefik.http.routers.emilija-dev.tls=true
      - traefik.http.routers.emilija-dev.tls.certresolver=le-emilija
      - traefik.docker.network=web
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true
